### ISSUE TITLE
While pulling data from database... it showing like this

### ISSUE THREAD

**Issue by Manikandan88564** [romanejaquez/orilla_fresca_app#19]
![image](https://user-images.githubusercontent.com/59675702/151651701-7c0907db-f9aa-4e14-ae5b-0b3d674edb39.png)

**Comment by Manikandan88564** [comment]
I try to run the app it stays in the splash page and doesn't move anywhere and popup error showing like above. Could you pls help with this error by any chance? :)

**Comment by romanejaquez** [comment]
Did you populate the data in Firebase? remember I preload the data from firebase from a collection called "orilla_fresca_data" prior to proceeding with the app. Make sure your firebase project information is correctly set up in the project (both google-services.json and GoogleService-Info.plist for IOS), and the collection is populated with data in Firebase.

**Comment by Manikandan88564** [comment]
yeah that works... i again populated datas into firebase then it fetched to my applicaton... thank you roman
