### ISSUE TITLE
Null Safety issues 

### ISSUE THREAD

**Issue by rebazjabar** [romanejaquez/orilla_fresca_app#7]
hello sir  , im so thanksfull that you share your knowledge with us  ,  but i have a question   i started the project   and i got most of the tasks from your videos about flutter , until part 5 i was continue but I'm stuck in this part .i have the problem in **SelectedCategoryPage.dart**   class   i watched many time of your video and did all the codes but  it wasn't fixed  , would you give  me a idea how to fix it ??? i used ? sign in the   SubCategory? subCategory; in **DetailsPage** but it wasn't solution? 

![SharedScreenshot](https://user-images.githubusercontent.com/32215251/126058481-c136808b-90c0-4de7-a06b-a09aa1ddf361.jpg)

**Comment by romanejaquez** [comment]
Did you change the type of the selectedCategory property in the SelectedCategoryPage to a nullable type as well? I definitely suggest you adding the "?" sign to the SubCategory property in the DetailsPage, so your code is now null safe, then make the change also in the selectedCategory here as well.

The code initially didn't support null safety, then I had to migrate to null safety, that's why there may be a conflict with the initial episodes so apologies for that inconvenience. Let me know if you run into further issues.

**Comment by rebazjabar** [comment]
[https://drive.google.com/drive/folders/1m5nJ3vuuRH-EvQVlAu2jV-DIUfHrF3WR?usp=sharing](url)   thanks u sir for answering my problem    ,, i did all the null safety  possibility   but it wasn't fixed. Sir i have uploaded the  **selecteCategoryPage**  and **DetailsPage** Classes  codes from this google drive  link  if u look those classes  tell me where is my error i will be glad .  many thanks for you

**Comment by rebazjabar** [comment]
[https://drive.google.com/drive/folders/1m5nJ3vuuRH-EvQVlAu2jV-DIUfHrF3WR?usp=sharing ](https://drive.google.com/drive/folders/1m5nJ3vuuRH-EvQVlAu2jV-DIUfHrF3WR?usp=sharingl)   thanks u sir for answering my problem    ,, i did all the null safety  possibility   but it wasn't fixed. Sir i have uploaded the  **selecteCategoryPage**  and **DetailsPage** Classes  codes from this google drive  link  if u look those classes  tell me where is my error i will be glad .  many thanks for you

**Comment by romanejaquez** [comment]
I looked at the files and I saw you did that correctly Yeah, once you change the models to using the nullable type, you also have to change the inner properties as well. I'd suggest do a full conversion of your project (if you haven't done it already). Not too cumbersome, just a few steps (use the migration https://dart.dev/null-safety/migration-guide#migration-tool). If that doesn't work, send me the whole code, i'll do it real quick for you if you can't.

**Comment by rebazjabar** [comment]
thanks sir i use this migration tool but also it show me the same problem it wasnt fixed .  
i have an idea to create the project to show the details about parts of computer so  your videos was best for may case. 
sir this is the codes that i have used if you have time, look these classes for me i will be glad and thankful 
[https://drive.google.com/drive/folders/1rxF93whogI6Hmz17Mo8zJ1jhrgGdo5yc?usp=sharing](https://drive.google.com/drive/folders/1rxF93whogI6Hmz17Mo8zJ1jhrgGdo5yc?usp=sharing) 
these are just the classes i have create  if you need full of the project  will upload in google drive .

**Comment by rebazjabar** [comment]
sir should i wait or give-up ?

**Comment by rebazjabar** [comment]
I'm so sorry sir for bothering you 
but should i wait for your answer  or giving up , you aren't answer me  ?

**Comment by romanejaquez** [comment]
Can you upload the full project please? For some reason I didn't receive notification of our last message so apologies for the delay. Please share the full project and I'll be able to assist. Thanks!

**Comment by rebazjabar** [comment]
[https://drive.google.com/drive/folders/1m5nJ3vuuRH-EvQVlAu2jV-DIUfHrF3WR?usp=sharing](https://drive.google.com/drive/folders/1m5nJ3vuuRH-EvQVlAu2jV-DIUfHrF3WR?usp=sharing)  here is the full codes. 

thanks a lot  dear , i appreciate it

**Comment by romanejaquez** [comment]
Hi @rebazjabar all I did was in the **selectedcategorypage.dart**, cast the passed subcategory into a SubCategory before passing it to the DetailsPage.

Before: 

Navigator.push(
                      context,
                      MaterialPageRoute(
                          builder: (context) => DetailsPage(
                              subCategory: this
                                  .selectedCategory!
                                  .subCategories![index]));

After:

Navigator.push(
                      context,
                      MaterialPageRoute(
                          builder: (context) => DetailsPage(
                              subCategory: this
                                  .selectedCategory!
                                  **.subCategories![index] as SubCategory**)));

Anyway, the way you are passing it here it's valid, but if you continue watching the videos, I eliminate this dependency and make it so the selected subcategory is not provided / injected via the constructor anymore, but the Provider State management strategy. You can keep it like this if you want, but the provider pattern strategy is cleaner and decoupled.

Updated code
https://drive.google.com/file/d/1lpx3KwLFKssVCb_K8y0eAS82bBeTmMCS/view?usp=sharing

Another piece of advice: never give up in front of adversities ;)

**Comment by rebazjabar** [comment]
I don't know how much I'm thankful for you are  helping me to do it 🥰🥰🥰
I appreciate u  god bless you 

 https://user-images.githubusercontent.com/32215251/126894332-b66d997d-4be8-4e9e-b62c-91f3d7216714.MOV

You are great master Thanks for your advice and for everything 🥰🥰🥰🥰

**Comment by organicnz** [comment]
@rebazjabar sorry mate, could you pls drop a dump of the firebase db by any chance? I couldn't figure out how to insert the data correctly right there :)

**Comment by rebazjabar** [comment]
@organicnz  sorry bro i did only 5 parts of his videos . i wasn't need firebase for my project , so that is why i didnt do it .

**Comment by organicnz** [comment]
> @organicnz sorry bro i did only 5 parts of his videos . i wasn't need firebase for my project , so that is why i didnt do it .
Oh, right, thanks for your comment mate :)
